import Link from "next/link";
import PageHeader from "@/components/portal/PageHeader";
import CoverageMap from "@/components/portal/CoverageMap";
import ShelfPhotos from "@/components/portal/ShelfPhotos";
import StatTile from "@/components/portal/charts/StatTile";
import InsightCard from "@/components/portal/InsightCard";
import { scope } from "@/lib/portal";
import { EMPTY_FILTERS, applyFilters } from "@/lib/portalFilters";
import { generateInsights } from "@/lib/insights";
import {
  headline,
  clientBrand,
  competitors,
  brandName,
  latest,
} from "@/lib/portalData";

export const metadata = {
  title: "Command Center",
};

/* The Decision Layer's surface. Unfiltered, latest visit — this page
   answers "what matters this cycle" for a reader who touches nothing.
   Everything below is generated by lib/insights.ts from data already
   on the page; nothing here is hand-written narrative. */
export default function CommandCenterPage() {
  const view = applyFilters(EMPTY_FILTERS, latest);
  const { presence, pricing, momentum } = generateInsights(view);

  const topPresence = presence[0];
  const rank = competitors.findIndex((c) => c.isClient) + 1;

  return (
    <>
      <PageHeader title="Command Center" lead="What matters this cycle" />

      {/* verdict line — the 5-second read */}
      <section className="mb-4 rounded-[18px] border border-line bg-white p-5 sm:p-6">
        {topPresence ? (
          <>
            <div className="flex items-center gap-2">
              <span
                className="dot"
                style={{
                  background:
                    topPresence.severity === "critical"
                      ? "var(--color-critical)"
                      : "var(--color-warn)",
                }}
              />
              <span className="t-eyebrow">
                Biggest issue this cycle · {scope.dataAsOf}
              </span>
            </div>
            <p className="mt-2 t-h3 !text-[19px] leading-snug">
              {topPresence.headline}
            </p>
            <p className="mt-1 text-sm text-ink-500">
              <span className="mono font-semibold text-ink-900">
                {topPresence.impact.label}
              </span>
              {" — "}
              {presence.length > 1
                ? `${presence.length - 1} more finding${presence.length > 2 ? "s" : ""} below.`
                : "the only issue flagged this cycle."}
            </p>
          </>
        ) : (
          <>
            <div className="flex items-center gap-2">
              <span className="dot" style={{ background: "var(--color-good)" }} />
              <span className="t-eyebrow">This cycle · {scope.dataAsOf}</span>
            </div>
            <p className="mt-2 t-h3 !text-[19px] leading-snug">
              Nothing crossed a threshold this cycle.
            </p>
            <p className="mt-1 text-sm text-ink-500">
              No district, channel, SKU or outlet is currently outside its
              expected range.
            </p>
          </>
        )}

        {momentum?.conceding && momentum.rivalBrandId && (
          <p className="mt-3 flex items-center gap-1.5 border-t border-line pt-3 text-[13px] text-ink-700">
            <svg viewBox="0 0 12 12" className="h-3 w-3 shrink-0" fill="none" stroke="var(--color-critical)" strokeWidth="1.8" strokeLinecap="round" aria-hidden>
              <path d="M2.5 3.5 6 8l1.7-2.2L9.5 8" />
            </svg>
            Momentum: {clientBrand.name} lost {Math.abs(momentum.clientDelta)}pt of
            share this cycle while{" "}
            <strong className="text-ink-900">
              {brandName(momentum.rivalBrandId)}
            </strong>{" "}
            gained {momentum.rivalDelta}pt.
          </p>
        )}
      </section>

      {/* KPI row */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile
          label="On-shelf availability"
          value={`${headline.availability}%`}
          delta={headline.availabilityDelta}
          goodDirection="up"
        />
        <StatTile
          label="Shelf share"
          value={`${headline.shelfShare}%`}
          delta={headline.shelfShareDelta}
          goodDirection="up"
          footnote={`Rank ${rank} of ${competitors.length} in category`}
        />
        <StatTile
          label="Price compliance"
          value={`${headline.priceCompliance}%`}
          footnote={`Across ${clientBrand.name} SKUs at RRP ±5%`}
        />
        <StatTile
          label="Active out-of-stocks"
          value={`${headline.activeOos}`}
          goodDirection="down"
          footnote={`${headline.oosDays} lost shelf-days this cycle`}
        />
      </div>

      <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
        {/* needs attention */}
        <section className="rounded-[18px] border border-line bg-white p-5 sm:p-6">
          <div className="mb-1 flex items-center justify-between gap-3">
            <h2 className="t-h3">Needs attention</h2>
            <span className="text-[12px] text-ink-400">
              Measured first, then by concentration
            </span>
          </div>
          <p className="mb-1 text-sm text-ink-500">
            {clientBrand.name}&apos;s biggest presence problems this cycle,
            each traceable to its own arithmetic — directly observed losses
            rank above formula estimates, and within each tier, facing-days
            at risk per outlet the finding touches, so a confirmed failure
            at one store outranks the same total cost spread thin across
            the whole city.
          </p>
          {presence.length ? (
            <ul>
              {presence.slice(0, 5).map((insight, i) => (
                <InsightCard key={insight.id} insight={insight} rank={i + 1} />
              ))}
            </ul>
          ) : (
            <p className="py-8 text-center text-sm text-ink-400">
              No presence issues cleared the reporting threshold this cycle.
            </p>
          )}
        </section>

        <div className="flex flex-col gap-4">
          {/* pricing watch — its own currency, kept separate from the
              facing-days ranking above */}
          <section className="rounded-[18px] border border-line bg-white p-5 sm:p-6">
            <h2 className="t-h3">Pricing watch</h2>
            <p className="mt-1 mb-1 text-sm text-ink-500">
              Outlets clustering price breaches. Measured in breaching
              readings, not facing-days — a different problem, a different fix.
            </p>
            {pricing.length ? (
              <ul>
                {pricing.slice(0, 3).map((insight) => (
                  <InsightCard key={insight.id} insight={insight} />
                ))}
              </ul>
            ) : (
              <p className="py-6 text-center text-sm text-ink-400">
                No outlet is clustering price breaches this cycle.
              </p>
            )}
          </section>

          {/* photography */}
          <section className="rounded-[18px] border border-line bg-white p-5 sm:p-6">
            <div className="mb-4">
              <h2 className="t-h3">From the shelf</h2>
              <p className="mt-1 text-sm text-ink-500">
                Geo-stamped in store on {scope.dataAsOf}. Every figure above
                traces back to frames like these.
              </p>
            </div>
            <ShelfPhotos />

            <dl className="mt-5 space-y-2 border-t border-line pt-4 text-[13px]">
              <Row label="Outlets audited" value={`${scope.posCount}`} />
              <Row label="SKUs tracked" value={`${scope.skuCount}`} />
              <Row
                label="Category gaps found"
                value={`${headline.totalOos}`}
                tone="critical"
              />
            </dl>
          </section>
        </div>
      </div>

      {/* coverage */}
      <section className="mt-4 rounded-[18px] border border-line bg-white p-5 sm:p-6">
        <div className="mb-5">
          <h2 className="t-h3">Coverage</h2>
          <p className="mt-1 text-sm text-ink-500">
            Live in {scope.city}. Select any governorate to see what it adds.
          </p>
        </div>
        <CoverageMap />
      </section>

      <p className="mt-4 text-[12px] text-ink-400">
        Every insight above is generated from a stated formula over this
        cycle&apos;s audit data — no forecasting, no machine learning.{" "}
        <Link href="/dashboard/shelf" className="font-semibold text-violet-ink hover:underline">
          Open Shelf
        </Link>{" "}
        for the full detail behind any of it.
      </p>
    </>
  );
}

function Row({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone?: "critical";
}) {
  return (
    <div className="flex items-center justify-between">
      <dt className="text-ink-500">{label}</dt>
      <dd
        className="mono font-semibold"
        style={{
          color: tone === "critical" ? "var(--color-critical)" : "var(--color-ink-900)",
        }}
      >
        {value}
      </dd>
    </div>
  );
}
